// ============ SERVICES DETAILED DATA ============
export const servicesData = [
  {
    id: 1,
    slug: "gmb-optimization",
    number: "01",
    name: "Google Business Profile",
    tagline: "GMB Optimization & Business Listing",
    heroTitle: "Dominate Local Search with Google Business Profile",
    heroDesc:
      "Get your business on Google Maps and rank #1 in local searches. Complete GMB setup, optimization, and management to bring more customers to your doorstep.",
    category: "Local SEO",
    duration: "1.5 Months for Ranking",
    image: "/services/gmb.jfif",
    gradient: "from-blue-500 to-cyan-400",
    shortDesc:
      "Complete GMB setup, optimization, posts, review strategy, and business listing management to improve local visibility.",
    fullDesc:
      "Google Business Profile (GMB) is your business's most powerful tool for local visibility. We provide complete GMB setup, optimization, and ongoing management to help your business rank at the top of Google Maps and local search results. Whether you're a restaurant, salon, coaching center, or any local business — we make sure your customers find you first.",
    features: [
      "Profile setup & verification",
      "Post management & updates",
      "Review strategy & response",
      "Business listing on 50+ platforms",
      "Local SEO optimization",
      "Google Maps ranking",
    ],
    whatYouGet: [
      "Complete Google Business Profile setup & verification",
      "Optimized business description with target keywords",
      "Professional photos and business categories",
      "Regular GMB posts (weekly updates, offers, events)",
      "Review management strategy & response templates",
      "Business listing on 50+ local directories",
      "Google Maps ranking optimization",
      "Monthly performance reports with insights",
    ],
    process: [
      {
        step: "01",
        title: "Audit & Setup",
        desc: "We audit your current GMB profile and optimize every section for maximum visibility.",
      },
      {
        step: "02",
        title: "Content & Photos",
        desc: "Upload high-quality photos, create optimized posts, and add all business details.",
      },
      {
        step: "03",
        title: "Listing & Citations",
        desc: "List your business on 50+ platforms for stronger local SEO signals.",
      },
      {
        step: "04",
        title: "Rank & Monitor",
        desc: "Track rankings, gather reviews, and continuously improve for #1 position.",
      },
    ],
    benefits: [
      "Rank #1 on Google Maps for local searches",
      "Get more calls, direction requests & visits",
      "Build trust with verified business profile",
      "Compete with big brands in your area",
      "Attract customers when they're ready to buy",
    ],
    idealFor: ["Restaurants", "Salons", "Retail Stores", "Coaching Centers", "Clinics", "Local Services"],
  },
  {
    id: 2,
    slug: "website-development",
    number: "02",
    name: "Website Development",
    tagline: "Landing • Basic • Pro • E-commerce",
    heroTitle: "Websites That Convert Visitors into Customers",
    heroDesc:
      "Custom-designed, fast-loading, SEO-friendly websites — from simple landing pages to full e-commerce stores. Built to grow your business.",
    category: "Development",
    duration: "1-2 Weeks Delivery",
    image: "/services/website.jfif",
    gradient: "from-cyan-400 to-teal-400",
    shortDesc:
      "Custom websites built for performance and conversion — from landing pages to full e-commerce stores.",
    fullDesc:
      "Your website is your digital storefront. We build custom, responsive, and SEO-optimized websites tailored to your business needs. Whether you need a simple landing page for lead generation, a professional business website, or a full-scale e-commerce store — we deliver websites that look great and perform even better.",
    features: [
      "Responsive design (mobile-first)",
      "SEO-optimized structure",
      "Fast loading & performance",
      "Payment gateway integration",
      "CMS for easy management",
      "Free SSL & hosting setup",
    ],
    whatYouGet: [
      "Custom design based on your brand",
      "Fully responsive (mobile, tablet, desktop)",
      "SEO-optimized structure & content",
      "Fast loading speed (< 3 seconds)",
      "Contact forms, WhatsApp integration",
      "Payment gateway (for e-commerce)",
      "Free SSL certificate & hosting setup",
      "1 month free support & maintenance",
    ],
    process: [
      {
        step: "01",
        title: "Discovery",
        desc: "We understand your business, goals, and design preferences.",
      },
      {
        step: "02",
        title: "Design",
        desc: "Create custom mockups and get your approval on the design.",
      },
      {
        step: "03",
        title: "Development",
        desc: "Build a fast, responsive, and SEO-friendly website.",
      },
      {
        step: "04",
        title: "Launch",
        desc: "Deploy your website with proper testing and free support.",
      },
    ],
    benefits: [
      "Look professional & build instant trust",
      "Convert visitors into paying customers",
      "Rank on Google for your business keywords",
      "Sell 24/7 without manual effort",
      "Own your digital presence completely",
    ],
    idealFor: ["Small Businesses", "Startups", "E-commerce Stores", "Personal Brands", "Professionals", "Agencies"],
  },
  {
    id: 3,
    slug: "social-media-marketing",
    number: "03",
    name: "Social Media Marketing",
    tagline: "Content • Growth • Branding",
    heroTitle: "Build a Powerful Brand on Social Media",
    heroDesc:
      "Strategic content, engaging visuals, and consistent posting across Instagram, Facebook, and LinkedIn to grow your audience and generate leads.",
    category: "Marketing",
    duration: "Results in 30-60 Days",
    image: "/services/social-media.jfif",
    gradient: "from-pink-500 to-rose-400",
    shortDesc:
      "Strategic social media management for Instagram, Facebook, and LinkedIn with content, creatives, and brand growth.",
    fullDesc:
      "Social media is where your customers spend their time. We manage your social media presence with strategic content planning, eye-catching creatives, and consistent engagement to build a loyal community around your brand. From growth strategy to daily execution — we handle it all.",
    features: [
      "Content calendar planning",
      "Creative design & videos",
      "Regular posting schedule",
      "Community management",
      "Hashtag & trend research",
      "Monthly performance reports",
    ],
    whatYouGet: [
      "Monthly content calendar (planned in advance)",
      "15-20 posts per month (posts, reels, stories)",
      "Professional creative design & videos",
      "Instagram, Facebook & LinkedIn management",
      "Community engagement & DM replies",
      "Hashtag research & trending strategies",
      "Story highlights, bio, and profile optimization",
      "Detailed monthly performance reports",
    ],
    process: [
      {
        step: "01",
        title: "Strategy",
        desc: "Define your brand voice, target audience, and content pillars.",
      },
      {
        step: "02",
        title: "Content Creation",
        desc: "Design engaging posts, reels, and videos that stop the scroll.",
      },
      {
        step: "03",
        title: "Publish & Engage",
        desc: "Post consistently and engage with your community daily.",
      },
      {
        step: "04",
        title: "Analyze & Improve",
        desc: "Track metrics, learn what works, and optimize continuously.",
      },
    ],
    benefits: [
      "Grow your followers organically",
      "Build brand awareness & recognition",
      "Generate leads through engaging content",
      "Establish authority in your niche",
      "Save time — we handle everything",
    ],
    idealFor: ["Brands", "Startups", "Restaurants", "Influencers", "Personal Brands", "E-commerce"],
  },
  {
    id: 4,
    slug: "whatsapp-marketing",
    number: "04",
    name: "WhatsApp Marketing",
    tagline: "Instant Customer Reach",
    heroTitle: "Reach Customers Directly on WhatsApp",
    heroDesc:
      "Bulk campaigns, automation, catalogs, and chatbots — everything you need to turn WhatsApp into your #1 sales channel.",
    category: "Marketing",
    duration: "Live in 3-5 Days",
    image: "/services/whatsapp.jfif",
    gradient: "from-green-500 to-emerald-400",
    shortDesc:
      "Reach your audience directly with WhatsApp campaigns, catalog setup, broadcasts, and automation flows.",
    fullDesc:
      "WhatsApp has 500 million users in India — and it's the most personal way to reach your customers. We set up WhatsApp Business API, create bulk broadcast campaigns, build product catalogs, and automate customer conversations to help you scale your business through WhatsApp marketing.",
    features: [
      "WhatsApp Business API setup",
      "Bulk broadcast campaigns",
      "Catalog & product listings",
      "Automated chat flows",
      "Customer segmentation",
      "Analytics & reporting",
    ],
    whatYouGet: [
      "WhatsApp Business API setup & verification",
      "Green tick verification support",
      "Bulk broadcast campaigns (unlimited)",
      "Product catalog setup with images & prices",
      "Automated welcome messages & chatbots",
      "Customer segmentation & tagging",
      "Order & inquiry management",
      "Detailed analytics & delivery reports",
    ],
    process: [
      {
        step: "01",
        title: "Setup",
        desc: "Configure WhatsApp Business API and verify your business.",
      },
      {
        step: "02",
        title: "Design",
        desc: "Create message templates, catalog, and automation flows.",
      },
      {
        step: "03",
        title: "Launch",
        desc: "Send your first campaign and start engaging customers.",
      },
      {
        step: "04",
        title: "Optimize",
        desc: "Track results, refine messaging, and scale what works.",
      },
    ],
    benefits: [
      "98% open rate (vs 20% for email)",
      "Direct 1-to-1 communication with customers",
      "Automate repetitive queries with chatbots",
      "Sell products directly via WhatsApp",
      "Build customer loyalty with personal touch",
    ],
    idealFor: ["E-commerce", "Local Businesses", "Restaurants", "Service Providers", "Coaching Institutes", "D2C Brands"],
  },
  {
    id: 5,
    slug: "google-meta-ads",
    number: "05",
    name: "Google & Meta Ads",
    tagline: "Paid Campaigns That Convert",
    heroTitle: "ROI-Driven Ad Campaigns That Deliver Results",
    heroDesc:
      "High-performing Google, Facebook, and Instagram ad campaigns designed to generate quality leads and boost sales — with measurable ROI.",
    category: "Paid Ads",
    duration: "Results in 7-14 Days",
    image: "/services/googleads.jfif",
    gradient: "from-orange-500 to-amber-400",
    shortDesc:
      "Performance-focused ad campaigns across Google, Facebook, and Instagram designed to generate leads and sales.",
    fullDesc:
      "Stop wasting money on ads that don't convert. We create data-driven Google Ads, Facebook Ads, and Instagram Ads campaigns focused on real business results. From keyword research to creative design to conversion tracking — we handle every aspect of your paid advertising for maximum ROI.",
    features: [
      "Campaign strategy & setup",
      "Ad creative design",
      "Keyword & audience research",
      "A/B testing & optimization",
      "Conversion tracking",
      "Weekly performance reports",
    ],
    whatYouGet: [
      "Complete Google Ads account setup",
      "Facebook & Instagram ads management",
      "Custom ad creatives (images & videos)",
      "Advanced keyword & audience research",
      "Landing page optimization suggestions",
      "A/B testing for higher conversions",
      "Conversion tracking & pixel setup",
      "Weekly performance reports & insights",
    ],
    process: [
      {
        step: "01",
        title: "Research",
        desc: "Analyze your business, competitors, and target audience deeply.",
      },
      {
        step: "02",
        title: "Setup",
        desc: "Create campaigns, ad creatives, and set up conversion tracking.",
      },
      {
        step: "03",
        title: "Launch",
        desc: "Launch campaigns with optimized targeting and budget.",
      },
      {
        step: "04",
        title: "Scale",
        desc: "Analyze data, optimize what works, and scale successful campaigns.",
      },
    ],
    benefits: [
      "Get quality leads within days",
      "Track every rupee of your ad spend",
      "Reach exact target audience",
      "Scale sales predictably",
      "Beat competitors in bidding",
    ],
    idealFor: ["E-commerce", "Service Businesses", "Local Businesses", "SaaS Startups", "Real Estate", "Education"],
  },
  {
    id: 6,
    slug: "youtube-marketing",
    number: "06",
    name: "YouTube Marketing",
    tagline: "Video Visibility & Growth",
    heroTitle: "Grow Your Brand with YouTube Marketing",
    heroDesc:
      "Complete YouTube strategy — channel optimization, video SEO, thumbnails, and ads to build a subscriber base and dominate search.",
    category: "Marketing",
    duration: "Growth in 45-90 Days",
    image: "/services/youtube.jfif",
    gradient: "from-red-500 to-pink-500",
    shortDesc:
      "YouTube strategy, video optimization, channel branding, and ads to grow your business through video content.",
    fullDesc:
      "YouTube is the world's 2nd largest search engine. We help you build a strong YouTube presence with channel setup, video SEO, engaging thumbnails, content strategy, and YouTube Ads. Whether you're a creator, coach, or business — we turn YouTube into a growth engine for your brand.",
    features: [
      "Channel setup & branding",
      "Video SEO optimization",
      "Thumbnail & title strategy",
      "YouTube Ads management",
      "Content calendar",
      "Subscriber growth strategy",
    ],
    whatYouGet: [
      "Complete channel setup with branding",
      "Custom banner, logo, and channel art",
      "Video SEO for every upload (title, tags, description)",
      "Click-worthy thumbnail designs",
      "Content calendar planning",
      "YouTube Ads campaign management",
      "Community post strategy",
      "Analytics reports & growth tracking",
    ],
    process: [
      {
        step: "01",
        title: "Setup",
        desc: "Optimize your channel with branding, banners, and about section.",
      },
      {
        step: "02",
        title: "Strategy",
        desc: "Plan content, keywords, and video topics for growth.",
      },
      {
        step: "03",
        title: "Publish",
        desc: "Upload with SEO-optimized titles, tags, and thumbnails.",
      },
      {
        step: "04",
        title: "Grow",
        desc: "Analyze performance and scale with ads if needed.",
      },
    ],
    benefits: [
      "Build a loyal subscriber base",
      "Rank videos on Google & YouTube search",
      "Earn from YouTube monetization",
      "Establish yourself as an authority",
      "Reach millions with viral potential",
    ],
    idealFor: ["Creators", "Coaches", "Brands", "Educators", "Businesses", "Personal Brands"],
  },
  {
    id: 7,
    slug: "digital-business-card",
    number: "07",
    name: "Digital Business Card",
    tagline: "Smart Networking",
    heroTitle: "Modern Digital Business Cards for Smart Networking",
    heroDesc:
      "Share your contact, social profiles, website, and portfolio with one tap or QR scan. Eco-friendly, always updated, and never runs out.",
    category: "Branding",
    duration: "Ready in 24-48 Hours",
    image: "/services/digitalcard.jfif",
    gradient: "from-violet-500 to-purple-500",
    shortDesc:
      "Modern digital business cards with contact details, social links, maps, and website access in one shareable format.",
    fullDesc:
      "Ditch paper cards forever. Our digital business cards let you share your complete professional identity with a single tap or QR scan — contact info, social profiles, website, portfolio, Google Maps location, and more. Custom-designed with your branding, always up-to-date, and eco-friendly.",
    features: [
      "Custom design & branding",
      "QR code integration",
      "Contact info & social links",
      "Google Maps integration",
      "Analytics tracking",
      "Easy sharing (WhatsApp, Email)",
    ],
    whatYouGet: [
      "Custom-designed digital business card",
      "Unique QR code for instant sharing",
      "All contact details in one place",
      "Social media profile links",
      "Website & portfolio links",
      "Google Maps integration",
      "One-tap WhatsApp & call buttons",
      "Analytics dashboard to track engagement",
    ],
    process: [
      {
        step: "01",
        title: "Design",
        desc: "Custom card design based on your brand identity.",
      },
      {
        step: "02",
        title: "Setup",
        desc: "Add all your links, contact info, and social profiles.",
      },
      {
        step: "03",
        title: "Deliver",
        desc: "Get your card, QR code, and shareable link within 48 hours.",
      },
      {
        step: "04",
        title: "Track",
        desc: "Monitor how many people view and interact with your card.",
      },
    ],
    benefits: [
      "Never run out of business cards",
      "Update info anytime without reprinting",
      "Eco-friendly & modern",
      "Track who viewed your card",
      "Share instantly via WhatsApp",
    ],
    idealFor: ["Professionals", "Freelancers", "Business Owners", "Sales Teams", "Consultants", "Networkers"],
  },
  {
    id: 8,
    slug: "seo-services",
    number: "08",
    name: "Search Engine Optimization",
    tagline: "Rank Higher Organically",
    heroTitle: "Rank #1 on Google with Proven SEO",
    heroDesc:
      "Complete SEO — on-page, off-page, technical, and local — to bring organic traffic that converts into customers month after month.",
    category: "SEO",
    duration: "3 Months for Results",
    image: "/services/seo.jfif",
    gradient: "from-indigo-500 to-blue-500",
    shortDesc:
      "SEO strategies including on-page, local, technical, and keyword optimization to boost search rankings.",
    fullDesc:
      "SEO is the most sustainable way to grow your business online. We provide complete SEO services — keyword research, on-page optimization, technical fixes, local SEO for Kota & Indore, backlink building, and continuous improvements — to rank your website on Google and drive organic traffic that lasts.",
    features: [
      "Keyword research & strategy",
      "On-page optimization",
      "Technical SEO audit",
      "Local SEO for Kota/Indore",
      "Backlink building",
      "Monthly ranking reports",
    ],
    whatYouGet: [
      "In-depth SEO audit of your website",
      "Keyword research (targeted for your business)",
      "On-page optimization (titles, meta, content)",
      "Technical SEO fixes (speed, mobile, structure)",
      "Local SEO for Kota, Indore & nearby cities",
      "Quality backlink building",
      "Content optimization & blog strategy",
      "Monthly ranking & traffic reports",
    ],
    process: [
      {
        step: "01",
        title: "Audit",
        desc: "Complete SEO audit to identify issues and opportunities.",
      },
      {
        step: "02",
        title: "Strategy",
        desc: "Keyword research and detailed SEO roadmap creation.",
      },
      {
        step: "03",
        title: "Optimize",
        desc: "Implement on-page, technical, and off-page optimizations.",
      },
      {
        step: "04",
        title: "Rank",
        desc: "Monitor rankings, build authority, and improve continuously.",
      },
    ],
    benefits: [
      "Get free organic traffic forever",
      "Rank #1 for buyer intent keywords",
      "Build long-term brand authority",
      "Lower customer acquisition cost",
      "Beat competitors in Google search",
    ],
    idealFor: ["Local Businesses", "E-commerce", "Service Providers", "SaaS", "Blogs", "Startups"],
  },
  {
    id: 9,
    slug: "ai-chatbot",
    number: "09",
    name: "AI Chatbot",
    tagline: "24/7 Smart Customer Support",
    heroTitle: "24/7 AI Chatbot That Never Sleeps",
    heroDesc:
      "Intelligent AI chatbots for websites, WhatsApp, and social media that answer queries, capture leads, and support customers around the clock.",
    category: "AI Automation",
    duration: "Live in 5-7 Days",
    image: "/services/ai-chatbot.jfif",
    gradient: "from-fuchsia-500 to-pink-500",
    shortDesc:
      "Intelligent AI chatbots for websites, WhatsApp, and social media that answer queries, capture leads, and support customers round the clock.",
    fullDesc:
      "Never miss a lead again. Our AI chatbots use advanced language models to understand customer queries and respond intelligently — 24/7 across your website, WhatsApp, Instagram, and Facebook. Perfect for lead capture, customer support, FAQs, and booking appointments — all without human intervention.",
    features: [
      "Custom AI training on your business",
      "Multi-platform integration",
      "Lead capture & qualification",
      "Human-like conversations",
      "Multi-language support",
      "Analytics & conversation reports",
    ],
    whatYouGet: [
      "Custom-trained AI chatbot for your business",
      "Website chat widget integration",
      "WhatsApp Business API chatbot",
      "Instagram & Facebook Messenger bot",
      "Lead capture forms within chat",
      "Multi-language conversation support",
      "Handoff to human agent option",
      "Detailed analytics & conversation logs",
    ],
    process: [
      {
        step: "01",
        title: "Discovery",
        desc: "Understand your business, FAQs, and customer journey.",
      },
      {
        step: "02",
        title: "Training",
        desc: "Train the AI on your products, services, and brand voice.",
      },
      {
        step: "03",
        title: "Integration",
        desc: "Deploy chatbot on website, WhatsApp, and social platforms.",
      },
      {
        step: "04",
        title: "Optimize",
        desc: "Monitor conversations and improve responses continuously.",
      },
    ],
    benefits: [
      "Never miss a lead — 24/7 availability",
      "Reduce customer support costs by 70%",
      "Instant responses build trust",
      "Handle 1000s of chats simultaneously",
      "Free up your team for high-value work",
    ],
    idealFor: ["E-commerce", "Service Businesses", "Real Estate", "Coaching", "Clinics", "SaaS"],
  },
  {
    id: 10,
    slug: "ai-call-agent",
    number: "10",
    name: "AI Call Agent",
    tagline: "Automated Voice Conversations",
    heroTitle: "AI Voice Agents That Talk Like Humans",
    heroDesc:
      "AI-powered voice agents that handle inbound calls, qualify leads, book appointments, and provide human-like responses in multiple languages.",
    category: "AI Automation",
    duration: "Setup in 7-10 Days",
    image: "/services/ai-call-agent.jfif",
    gradient: "from-purple-500 to-indigo-500",
    shortDesc:
      "AI-powered voice agents that handle inbound calls, qualify leads, book appointments, and provide human-like responses in multiple languages.",
    fullDesc:
      "Handle every customer call without hiring a call center. Our AI voice agents speak naturally in Hindi, English, and other Indian languages — answering queries, booking appointments, qualifying leads, and providing instant support. Available 24/7 at a fraction of the cost of human agents.",
    features: [
      "Human-like voice conversations",
      "Hindi & English support",
      "Appointment booking",
      "Lead qualification",
      "CRM integration",
      "Call recording & analytics",
    ],
    whatYouGet: [
      "Custom AI voice agent trained for your business",
      "Multi-language support (Hindi, English + more)",
      "24/7 inbound call handling",
      "Automatic appointment booking",
      "Lead qualification & scoring",
      "Integration with your CRM/tools",
      "Call recordings & transcripts",
      "Real-time analytics dashboard",
    ],
    process: [
      {
        step: "01",
        title: "Setup",
        desc: "Configure your business phone number and AI voice.",
      },
      {
        step: "02",
        title: "Training",
        desc: "Train AI on your services, pricing, and conversation flows.",
      },
      {
        step: "03",
        title: "Testing",
        desc: "Test with real scenarios and refine responses.",
      },
      {
        step: "04",
        title: "Launch",
        desc: "Go live and start handling calls automatically.",
      },
    ],
    benefits: [
      "Never miss a call — 24/7 availability",
      "Handle 100s of calls simultaneously",
      "80% cheaper than human agents",
      "Consistent quality every call",
      "Speaks multiple Indian languages",
    ],
    idealFor: ["Real Estate", "Clinics", "Restaurants", "Service Providers", "Coaching Centers", "E-commerce"],
  },
  {
    id: 11,
    slug: "appointment-booking-tool",
    number: "11",
    name: "Appointment Booking Tool",
    tagline: "Automated Scheduling System",
    heroTitle: "Smart Appointment Booking System",
    heroDesc:
      "Let customers book appointments 24/7 via your website, WhatsApp, or GMB — with automatic reminders, confirmations, and calendar sync.",
    category: "Automation",
    duration: "Setup in 3-5 Days",
    image: "/services/appointment-booking.jfif",
    gradient: "from-teal-500 to-cyan-500",
    shortDesc:
      "Smart appointment booking systems integrated with your website, WhatsApp, and GMB — with reminders, confirmations, and calendar sync.",
    fullDesc:
      "Stop wasting time on manual scheduling. Our appointment booking tools let customers book slots directly through your website, WhatsApp, or Google Business Profile. With automated reminders, calendar sync, and payment collection — you save hours every week while providing a professional booking experience.",
    features: [
      "Website booking widget",
      "WhatsApp booking integration",
      "Google Calendar sync",
      "Automated reminders (SMS/Email)",
      "Payment collection",
      "Multi-staff scheduling",
    ],
    whatYouGet: [
      "Custom booking system for your business",
      "Website widget for online booking",
      "WhatsApp appointment booking",
      "Google Business Profile integration",
      "Google Calendar / Outlook sync",
      "Automated SMS & email reminders",
      "Payment gateway integration",
      "Multi-staff & multi-service management",
    ],
    process: [
      {
        step: "01",
        title: "Setup",
        desc: "Configure services, staff, availability, and pricing.",
      },
      {
        step: "02",
        title: "Integrate",
        desc: "Connect with your website, WhatsApp, and calendar.",
      },
      {
        step: "03",
        title: "Automate",
        desc: "Setup reminders, confirmations, and payment flows.",
      },
      {
        step: "04",
        title: "Launch",
        desc: "Go live and let customers book 24/7.",
      },
    ],
    benefits: [
      "Save 10+ hours per week on scheduling",
      "Reduce no-shows with auto reminders",
      "Accept bookings 24/7 automatically",
      "Collect payments upfront",
      "Professional customer experience",
    ],
    idealFor: ["Clinics", "Salons", "Consultants", "Fitness Trainers", "Service Providers", "Coaching Centers"],
  },
  {
    id: 12,
    slug: "ai-business-tools",
    number: "12",
    name: "AI Business Tools",
    tagline: "Automation • Insights • Growth",
    heroTitle: "Custom AI Tools to Automate Your Business",
    heroDesc:
      "Tailored AI solutions for content generation, data analysis, workflow automation, and business intelligence — built specifically for your needs.",
    category: "AI Automation",
    duration: "Custom Timeline",
    image: "/services/ai-business-tools.jfif",
    gradient: "from-yellow-500 to-orange-500",
    shortDesc:
      "Custom AI-powered business tools for automation, content generation, data analysis, and workflow optimization tailored to your business needs.",
    fullDesc:
      "Every business is unique — and so are our AI solutions. We build custom AI-powered tools tailored to your specific business needs. From automating repetitive tasks and generating content to analyzing data and creating custom dashboards — we help you leverage AI to work smarter, not harder.",
    features: [
      "Custom AI tool development",
      "Workflow automation",
      "Content generation systems",
      "Data analysis & reports",
      "CRM & tool integrations",
      "Ongoing support & updates",
    ],
    whatYouGet: [
      "Custom AI solution designed for your business",
      "Workflow automation setup",
      "AI content generation tools",
      "Data analysis & reporting dashboards",
      "Integration with existing tools (CRM, ERP)",
      "Training for your team",
      "Documentation & user guides",
      "3 months of free support & updates",
    ],
    process: [
      {
        step: "01",
        title: "Discovery",
        desc: "Understand your workflows and identify automation opportunities.",
      },
      {
        step: "02",
        title: "Design",
        desc: "Design custom AI solution architecture for your needs.",
      },
      {
        step: "03",
        title: "Build",
        desc: "Develop, test, and deploy your custom AI tool.",
      },
      {
        step: "04",
        title: "Support",
        desc: "Train your team and provide ongoing improvements.",
      },
    ],
    benefits: [
      "Automate boring repetitive tasks",
      "Save 20+ hours per week",
      "Make data-driven decisions faster",
      "Scale operations without hiring",
      "Custom-built for YOUR business",
    ],
    idealFor: ["Startups", "SMEs", "Agencies", "E-commerce", "Consultants", "Enterprises"],
  },
];


// ============ HELPERS ============
export const getServiceBySlug = (slug) => {
  return servicesData.find((service) => service.slug === slug);
};

export const getRelatedServices = (currentId, limit = 3) => {
  return servicesData.filter((service) => service.id !== currentId).slice(0, limit);
};